### ISSUE TITLE
Why are those types unsafe?

### ISSUE THREAD

**Issue by dumbFeng** [breml/errchkjson#20]
Why are those types of float32, float64 and interface{} unsafe?

**Comment by breml** [comment]
@dumbFeng In the context of `errchkjson` a type is considered unsafe, if it might return an error, when the type is encoded to JSON.

`float32` and `float64` in Go (as well as all other languages, which implement [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754)) allow two special values, one for +infinite and one for -infinite, that do not have a representation in JSON, because a number in JSON is always a positive or negative number, optionally with fraction and exponent. If one encodes a `float32` or `float64` which contains one of these special values, the encoding to JSON will return an error (see: https://github.com/golang/go/blob/master/src/encoding/json/encode.go#L575-L577). While this case might be very unlikely, it is still possible and therefore the encoding of float values can not be considered 100% safe.

In the case of the `interface{}` we have no information about the type at all, so we can not know, if the type, that will be passed at runtime, is safe or unsafe. If the type would be a function or a complex number, the encoding to JSON would fail. Therefore we need to consider `interface{}` always as unsafe.

**Comment by dumbFeng** [comment]
Thank for your reply! Got it!



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Lucas ***@***.***> |
| Date | 10/26/2022 03:18 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [breml/errchkjson] Why are those types unsafe? (Issue #20) |

@dumbFeng In the context of errchkjson a type is considered unsafe, if it might return an error, when the type is encoded to JSON.

float32 and float64 in Go (as well as all other languages, which implement IEEE 754) allow two special values, one for +infinite and one for -infinite, that do not have a representation in JSON, because a number in JSON is always a positive or negative number, optionally with fraction and exponent. If one encodes a float32 or float64 which contains one of these special values, the encoding to JSON will return an error (see: https://github.com/golang/go/blob/master/src/encoding/json/encode.go#L575-L577). While this case might be very unlikely, it is still possible and therefore the encoding of float values can not be considered 100% safe.

In the case of the interface{} we have no information about the type at all, so we can not know, if the type, that will be passed at runtime, is safe or unsafe. If the type would be a function or a complex number, the encoding to JSON would fail. Therefore we need to consider interface{} always as unsafe.
