### ISSUE TITLE
non nil/zero *time.Time - how is that unsafe?

### ISSUE THREAD

**Issue by ldemailly** [breml/errchkjson#22]
Possibly an faq but why

```golang
	ShortestCertExpiry *time.Time `json:"ShortestCertExpiry,omitempty"`
```

generates

Error return value of `encoding/json.MarshalIndent` is not checked: unsafe type `*time.Time` found (errchkjson)

I am not aware of which value of time.Time can't be serialized?

**Comment by breml** [comment]
´*time.Time´ implements the ´json.Marshaler´ interface, which returns an error. Therefore encoding this type can not be considered safe by errchkjson.

**Comment by ldemailly** [comment]
Thanks for the quick reply, I do get the theory but in practice, which value of time.Time would fail to marshal? (I wouldn't mind adding an `err` to my code but then I'd need to have bad value to keep my test coverage at 100%)

**Comment by breml** [comment]
First of all, it is not required for the `MarshalJSON` to actually return an error for errchkjson to consider such a type as unsafe, since the actual implementaion is not inspected. Implementing the interface is enough, since it permits to return an error.
In the case of `time.Time`, I checked the actual implementaion for you.
In the implementation of [`time.MarshalJSON`](https://cs.opensource.google/go/go/+/refs/tags/go1.20.2:src/time/time.go;l=1343) you can see, that `t.appendStrictRFC3339` returns an error. In the implementation of [`t.appendStrictRFC3339`](https://cs.opensource.google/go/go/+/refs/tags/go1.20.2:src/time/format_rfc3339.go;drc=70f98a251efdbfd619c4ff466a43da299ad04752;l=62) there are two error cases. I think, having a `time.Time` with a year outside of 0 - 9999 might be the simplest case to force an error in the tests.

**Comment by ldemailly** [comment]
Oh nice, thanks! Ok for me the date comes from a x509 certificate so a date outside of the current era is not possible, so I'll just put that comment as my // nolint - thanks a lot for the very informative answer and digging up that corner case!
